import LoyolaFormal

#print axioms Loyola.det_W
#print axioms Loyola.det_W_ne_zero
#print axioms Loyola.features_span
#print axioms Loyola.K13_degrees_in_range
#print axioms Loyola.K13_gamma_absorbed
#print axioms Loyola.K13_upper_attained
#print axioms Loyola.K2K3_lower_attained
#print axioms Loyola.LO_le_sqrt_mul_sqrt
#print axioms Loyola.LO_le_sqrt_prod
#print axioms Loyola.LO_le_upper
#print axioms Loyola.LO_ratio_bound
#print axioms Loyola.logSumExp_convex
#print axioms Loyola.LOm_le_upper
#print axioms Loyola.lower_le_LO
#print axioms Loyola.lower_le_LOm
#print axioms Loyola.lower_le_psi
#print axioms Loyola.one_sub_q_sq
#print axioms Loyola.P1_card
#print axioms Loyola.P1_degree_consistent
#print axioms Loyola.P1_eq_replicates
#print axioms Loyola.P1_ne_P2
#print axioms Loyola.P1_P2_same_pure_gamma
#print axioms Loyola.P1_P2_same_q
#print axioms Loyola.P1_P2_same_qN
#print axioms Loyola.P2_card
#print axioms Loyola.P2_degree_consistent
#print axioms Loyola.P2_eq_replicates
#print axioms Loyola.par1_valid
#print axioms Loyola.par2_valid
#print axioms Loyola.psi_le_upper
#print axioms Loyola.psi_mul_psi_eq_sq
#print axioms Loyola.q_le_imbalance_max
#print axioms Loyola.q_only_direction
#print axioms Loyola.ratio_bound
#print axioms Loyola.tree1_profile
#print axioms Loyola.tree2_profile
#print axioms Loyola.trees_same_degree_sequence
#print axioms Loyola.witness_span
